Repository fossguild/naja, pull requests merged in 2025-10, with the labels that each got.

#34 repo: add pre-commit hooks for linting and formatting
  .gitignore
  .pre-commit-config.yaml
  AUTHORS
  README.md
  assets/font/README.txt
  docs/CONTRIBUTING.md
  docs/conventions.md
  docs/exercise.md
  docs/issues.md
  docs/manual.md
  kobra.py
  pyproject.toml
Labels: chore

#30 Chore/CI Actions
  .github/workflows/ci.yml
  docs/CONTRIBUTING.md
  docs/conventions.md
  docs/manual.md
Labels: chore

#32 Fix horizontal alignment of score text
  kobra.py
Labels: bug, good first issue

#14 feat: increase snake speed after eating an apple (Closes #13)
  kobra.py
Labels: enhancement
